### ISSUE TITLE
unable to get Cockroach ARRAY underlying type

### ISSUE THREAD

**Issue by pallavJha** [glerchundi/sqlboiler-crdb#18]
Error while model creation
````bash
$ cockroach version
Build Tag:    v2.1.1
Build Time:   2018/11/19 18:32:38
Distribution: CCL
Platform:     windows amd64 (x86_64-w64-mingw32)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  4523f9819d2dde9b054fc8faf1568e107f130986
Build Type:   release
````

````bash
$ go version
go version go1.11.1 windows/amd64
````

init.sql
```sql
CREATE TABLE scripts
(
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                   string                   NOT NULL UNIQUE,
  content                string                   NOT NULL,
  type                   INT2                     NOT NULL,
  default_execution_time FLOAT                    NOT NULL,
  std_in                 STRING                   NOT NULL,
  status                 INT2                     NOT NULL,
  comments               STRING ARRAY             NOT NULL,
  created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
  deleted_at             TIMESTAMP WITH TIME ZONE NULL,
  UNIQUE (name)
);
````

Error:
````bash
$ sqlboiler --wipe crdb --config=./configs/config.dev.toml
panic: unable to get Cockroach ARRAY underlying type [recovered]
        panic: interface conversion: string is not error: missing method Error

goroutine 1 [running]:
github.com/glerchundi/sqlboiler-crdb/driver.(*CockroachDBDriver).Assemble.func1(0xc000089c98, 0xc000089c90)
        C:/Users/PallavJha/code/pkg/mod/github.com/glerchundi/sqlboiler-crdb@v0.0.0-20181113123126-741c0b1e6ecc/driver/crdb.g
o:56 +0x78
panic(0x671c20, 0x712700)
        C:/Go/src/runtime/panic.go:513 +0x1c7
github.com/glerchundi/sqlboiler-crdb/driver.(*CockroachDBDriver).TranslateColumnType(0xc00005ca40, 0xc000066e90, 0x8, 0x0, 0x
0, 0xc000066ed5, 0x5, 0x0, 0x0, 0x0, ...)
        C:/Users/PallavJha/code/pkg/mod/github.com/glerchundi/sqlboiler-crdb@v0.0.0-20181113123126-741c0b1e6ecc/driver/crdb.g
o:484 +0x1df0
github.com/volatiletech/sqlboiler/drivers.Tables(0x715a80, 0xc00005ca40, 0x6c5cfe, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/PallavJha/code/pkg/mod/github.com/volatiletech/sqlboiler@v3.0.1+incompatible/drivers/interface.go:103 +0x309

github.com/glerchundi/sqlboiler-crdb/driver.(*CockroachDBDriver).Assemble(0xc00005ca40, 0xc0001083f0, 0x0, 0x0, 0x0)
        C:/Users/PallavJha/code/pkg/mod/github.com/glerchundi/sqlboiler-crdb@v0.0.0-20181113123126-741c0b1e6ecc/driver/crdb.g
o:97 +0x60e
github.com/volatiletech/sqlboiler/drivers.DriverMain(0x715340, 0xc00005ca40)
        C:/Users/PallavJha/code/pkg/mod/github.com/volatiletech/sqlboiler@v3.0.1+incompatible/drivers/driver_main.go:37 +0x30
c
main.main()
        C:/Users/PallavJha/code/pkg/mod/github.com/glerchundi/sqlboiler-crdb@v0.0.0-20181113123126-741c0b1e6ecc/main.go:9 +0x
44
Error: unable to initialize tables: unable to fetch table data: driver (C:\Users\PallavJha\code\bin\sqlboiler-crdb.exe) exite
d non-zero: exit status 2
````

encountered the same error after changing the `DDL`  to 

````sql
CREATE TABLE scripts
(
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                   string                   NOT NULL UNIQUE,
  content                string                   NOT NULL,
  type                   INT2                     NOT NULL,
  default_execution_time FLOAT                    NOT NULL,
  std_in                 STRING                   NOT NULL,
  status                 INT2                     NOT NULL,
  comments               STRING[]                 NOT NULL,
  created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
  deleted_at             TIMESTAMP WITH TIME ZONE NULL,
  UNIQUE (name)
);
````

BTW there weren't any errors when the DDL was:
````sql
CREATE TABLE scripts
(
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                   string                   NOT NULL UNIQUE,
  content                string                   NOT NULL,
  type                   INT2                     NOT NULL,
  default_execution_time FLOAT                    NOT NULL,
  std_in                 STRING                   NOT NULL,
  status                 INT2                     NOT NULL,
  created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
  deleted_at             TIMESTAMP WITH TIME ZONE NULL,
  UNIQUE (name)
);

`````

**Comment by glerchundi** [comment]
Sorry for the radio silence, I'll take a look at this today and will tell you something.

**Comment by glerchundi** [comment]
Traced. This is related to this change: https://github.com/cockroachdb/cockroach/pull/28945. In CockroachDB 2.1 data types were moved to `information_schema.columns.crdb_sql_type` column. Will try to fix as soon as possible.

Thanks for reporting.

**Comment by glerchundi** [comment]
@pallavJha I pushed a fix right now PTAL and reopen in case it doesn't make it for you.

**Comment by themontem** [comment]
@glerchundi, Facing this issue, after building a new binary from the master branch at commit (97aea0ea)
```
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled data type int2, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled data type float8, falling back to string
Warning: Unhandled nullable data type int8, falling back to null.String
Warning: Unhandled data type float8, falling back to string
Warning: Unhandled nullable data type float8, falling back to null.String
Warning: Unhandled data type int2, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled nullable data type timestamptz, falling back to null.String
Warning: Unhandled data type timestamptz, falling back to string
Warning: Unhandled data type timestamptz, falling back to string
```

**Comment by glerchundi** [comment]
Test with latest, pushed another fix concretely for this data type.

**Comment by glerchundi** [comment]
PTAL to latest @themontem.

**Comment by themontem** [comment]
Awesome, working fine now. Thanks.
